services:
  - type: worker
    name: ipo-scraper
    env: node
    plan: starter
    buildCommand: |
      npm install
      npx playwright install --with-deps chromium
    startCommand: "npm start"
    autoDeploy: true
